## Python 6

In [1]:
import numpy as np


In this week's workshop we'll cover:
1. logical vectors 
2. formative assessment 

### Logical vectors

In [12]:
x = np.array([1,2,3,4,5])
x > 3   #logical array

array([False, False, False,  True,  True])

In [16]:
x == 3

array([False, False,  True, False, False])

In [17]:
x >= 3

array([False, False,  True,  True,  True])

In [18]:
np.sum( x > 3)  #in Python:  1 means True, 0 means False

2

In [19]:
np.any( x> 3) # True if any of the elements of the logical vector are True

True

In [20]:
np.all (x<3) # True only if ALL the elements of the logical vector are True

False

In [21]:
np.all (x > -3) 

True

#### Example: in the file stress.dat, identify whether any of the stress values exceed 100.

In [25]:
# We could code some for-loops and use an if statement
# Alternatively the following code is much shorter and more readable:

import numpy as np
data = np.loadtxt('stress.dat')
np.any( data[1:,:] > 100 )

True

#### Working with logical vectors

In [34]:
(x > 3) & (x <= 4)   #parenthesis crucial here or Python will falsely interpret what is written

array([False, False, False,  True, False])

In [35]:
(x > 1) | (x < 5)

array([ True,  True,  True,  True,  True])

In [36]:
(x > 1) or (x < 5)   #This fails because "or" and "and" are only for a single object, not a vector.

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### Referencing with logical vectors

In [37]:
indices = x > 3
print(indices)
x[indices]  #keep only those values with an index of "True"

[False False False  True  True]


array([4, 5])

In [39]:
x [ x>3 ]   #shorthand

array([4, 5])

#### Example: in the file stress.dat, identify the times at which the stress in column 2 exceeds -125.

In [1]:
import numpy as np
data = np.loadtxt('stress.dat')

indices = data[:,1] > -125
data[indices,0]

array([ 615.,  616.,  617.,  618.,  619.,  620., 1392., 1393., 1394.,
       1395., 1396., 1397., 1398., 1399., 1556., 1557., 1558., 1559.,
       1560., 1561., 1562., 1563., 1564., 1565., 1566., 1567., 1568.,
       3279., 3280., 3281., 3282., 3283., 3284., 3285.])

#### Example: in the file stress.dat, identify the times at which the stress in column 2 exceeds -125 AND the stress in column 3 is less than -141


In [61]:
import numpy as np
data = np.loadtxt('stress.dat')

indices = (data[:,1] > -125) & (data[:,2] < -141)
data[indices,0]

array([ 620., 1397., 1398., 1399., 3279., 3280., 3281., 3282., 3283.,
       3284., 3285.])

## Tasks
1.  For the vector v given below, define a new vector w to be all the elements between 4 and 6 of v and display the maximum value of w.

In [2]:
np.random.seed(1)
v = np.random.uniform(low=0, high=10, size=500)


In [3]:
w = v[(v >= 4) & (v<=6)]
w.max()

5.991103076458783

2. 
    1. Find all the values of v that have a sine value of less than 0. 
    2. Find all the values of v that have a sine value of between -0.5 and 0?
    How many values are there that satisfy this criteria?

In [6]:
w1 = v[ np.sin(v)<0]
w2=  v[ (np.sin(v)<0 ) & (np.sin(v) > -0.5) ]
print('Number of values is ', w2.shape[0])

Number of values is  83


3. Suppose temperature and ice-cream consumption are given on a
daily basis by the first and second columns of the array A given below.
Find the mean temperature for those days for which ice-cream
consumption exceeds 135.

What was the temperature corresponding to the maximum number of ice creams?

In [28]:
A = np.array( [[20,21,24, 25, 26, 28, 26, 28, 24, 30, 28, 29, 24, 24, 23, 22, 21], 
              [100,120,98, 140, 143, 134, 128, 152, 120, 140, 150, 151, 132, 134, 132, 122, 121]]).T
             


In [45]:
temperature = A[:,0]
ice_creams = A[:,1]
print('Mean temperature: ', temperature[ice_creams > 135].mean() )

print('Temperature corresponding to max consumption of ice creams ', temperature[ice_creams.argmax()] )
                                                                        


Mean temperature:  27.666666666666668
Temperature corresponding to max consumption of ice creams  28


4. The roots of the equation
$$ \tan(x) -x - 1/2 = 0$$
can be found numerically by creating an equally spaced grid of x-values between 0 and 1 of size 1000000, and find those values of $x$ for which the equation is satisfied within a tolerance. To do this, define an appropriate vector $y$ (which is the left hand side of the equation) and use logical vectors to find the elements of x for which the absolute value of each element of y is less than (say) a tolerance of 0.001. Display to the screen the maximum root you find. 


In [43]:
x = np.linspace(0,1,1000000)
y = np.tan(x) - x - 0.5
tol = 0.001
x[y < tol].max()

0.9754759754759754