## Python 4

In this workshop, we'll look at
1. Conditional statements
2. ..and loops..
3. Formatted output


In [1]:
import numpy as np

# Conditional (if) statements

In [12]:
x = 2
if x==3:    #no need for brackets i.e. don't type "if (x==3):""
    print('Error')   #tab indent

In [13]:
if x==3:    
    print('Error')  
else:
    print('Everything is OK')
    

Everything is OK


In [39]:
x=40
if x==3:    
    print('Error')  
elif x<-20:
    print('Oh dear') 
elif x==4:
    print('File problem')
else:
    print('Everything is OK')

Everything is OK


In [11]:
# Some other comparisons...
x = 1
if x>1:
    print("Greater than 1")
if x<1:
    print("less than 1")
if x>=1:
    print("At least 1")
if x!=1:
    print("Not equal to 1")

At least 1


# Combining loops and if statements

In [21]:
# create a dataset:
x = np.random.normal(size=1000)

for i in range(1000):
    if x[i] > 3:
        print('Element of x with index ',i,' exceeds 3')

Element of x with index  219  exceeds 3
Element of x with index  611  exceeds 3
Element of x with index  665  exceeds 3
Element of x with index  949  exceeds 3


In [32]:
# Use break to "break out of the loop"
np.random.seed(1)
x = np.random.normal(size=1000)

for i in range(1000):
    if x[i] > 3:
        print('Error')
        break

Error


In [34]:
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [36]:
# display diagonal elements:
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        if i==j:
            print(A[i,j])

1
6
11
16


In [49]:
# counting items
np.random.seed(1)
x = np.random.normal(size=1000)
total = 0

for i in range(1000):
    if x[i] > 3:
        total += 1
print('Total number of items exceeding 3 is ', total)

Total number of items exceeding 3 is  3


In [53]:
#  Use of logical "and"
np.random.seed(1)
x = np.random.normal(size=1000)
total = 0

for i in range(1000):
    if x[i] > 3 and x[i] < 5:
        total += 1
print('Total number of items exceeding 3 but less than 5 is ', total)

Total number of items exceeding 3 but less than 5 is  3


In [2]:
#  Use of logical "or"
np.random.seed(1)
x = np.random.normal(size=1000)
total = 0

for i in range(1000):
    if x[i] > 3 or x[i] < -3:
        total += 1
print('Total number of items either less than -3 or greater than 3 is ', total)

Total number of items either less than -3 or greater than 3 is  4


### Getting user input

In [8]:
x = input('Type a number ')  #string
print(x)

Type a number  3


3


In [9]:
type(x)

str

In [10]:
x = float(input('Type a number '))  #float i.e. decimal number
print(x)
type(x)

Type a number  3.45


3.45


float

In [11]:
x = int(input('Type a number '))  #int i.e. integer number
print(x)
type(x)

Type a number  43


43


int

## Tasks:

1. The discriminant $b^2 – 4ac$ determines the nature of the roots of a quadratic equation $ax^2 + bx +c = 0$. 
   
   
Write some code that asks for the coefficients a, b and c from the user, and calculates
the discriminant $b^2 – 4ac$.
Perform a test to see whether the discriminant is zero, positive or negative and display a message to the
user saying which category it falls into.

In [5]:
a = float(input("Enter a"))
b = float(input("Enter b"))
c = float(input("Enter c"))
disc = b**2 - 4 * a * c
if disc == 0:
    print("Discrimant is zero")
elif disc > 0:
    print("Discrimant is positive")
else:
    print("Discrimant is negative")


Enter a 0.1
Enter b 23
Enter c 1


Discrimant is positive


In [15]:
m = float(input("Enter budget"))
if m > 100:
    print("Buy clothes")
elif 100 > m > 10:
    print("Buy food")
elif 10>m>0: 
    print("Buy drink")
else:
    print("No idea!")


Enter budget 11


Buy food


In [17]:
data = np.zeros(10)
for i in range(10):
    data[i] = float(input("Enter a number"))

number_rejects = 0
for i in range(10):
    if data[i] > 3:
        number_rejects += 1
print("Total number of rejected items is ", number_rejects)

Enter a number 3
Enter a number 4
Enter a number 3
Enter a number 5
Enter a number 6
Enter a number 7
Enter a number 6
Enter a number 5
Enter a number 4
Enter a number 5


Total number of rejected items is  8


In [25]:
wind_speeds = np.array([30,31,20,25,24,19,34,45,50,51,49,51,52,58,57,49,43,42,39,32,33,31,30,29])
len(wind_speeds)

24

In [36]:
def test_vector(wind):
    ''' Function to test the input vector wind to see if a storm occurred'''
    
    for i in range(len(wind)-3):  #remember indents..
        if wind[i] > 50 and wind[i+1] > 50 and wind[i+2] > 50 and wind[i+3] > 50:
            print("Storm occurred")

test_vector(wind_speeds)

Storm occurred


## Formatted output

In [60]:
# easiest way to output variables:
x = 3
y = 5
print('x takes the value ', x)
print('x takes the value ', x, ' while y takes the value of ', y)


x takes the value  3
x takes the value  3  while y takes the value of  5


#### Formatted output: method 1

In [73]:
print('The value of pi is approximately %.3f.' % np.pi)  # 3 decimal places
print('The value of 0.01 pi is approximately %.10f.' % (np.pi*0.01)) # 10 decimal places
print('The value of 1,000,000 pi is approximately %.3e.' % (np.pi*1e6)) #exponential notation, 3 decimal places.
print('The value of pi is approximately %d' % np.pi)  # integer


The value of pi is approximately 3.142.
The value of 0.01 pi is approximately 0.0314159265.
The value of 1,000,000 pi is approximately 3.142e+06.
The value of pi is approximately 3


In [76]:
x,y = 2,3
print('The values of x and y are %d and %d\n'% (x,y) )

The values of x and y are 2 and 3



#### Formatted output: method 2

In [40]:
print('{0} and {1}'.format('bread', 'cheese'))

bread and cheese


In [77]:
print('{1} and {0}'.format('bread', 'cheese'))

cheese and bread


In [78]:
print('{0:d} and {1:d}'.format(x, y))

2 and 3


In [80]:
print('{0:.3f} and {1:.5f}'.format(x, y))

2.000 and 3.00000


In [81]:
for i in range(10):
    print('{0:4d}, {1:4d}'.format(i,i**2))

   0,    0
   1,    1
   2,    4
   3,    9
   4,   16
   5,   25
   6,   36
   7,   49
   8,   64
   9,   81


## Tasks

1. Prompt the user to enter a decimal number over 1000. Display the number to 3 decimal places, and also using exponential notation to 3 decimal places.

2. The vector rho defined below represents density. All its values should be positive, but you suspect there might be a mistake. 
Loop over its elements one by one. If the ith element is negative then display the element (to 2 decimal places), and its index i, to the screen with some explanatory text.
If you find a negative element, then there is no need to continue checking and you can break out of the loop.


In [29]:
rho = np.array([0.1197403 , 1.44653085, 0.03276663, 0.24733591, 0.27777791 ,1.51892745,
 0.24998435 ,0.43247599 ,-0.78166048 ,1.18592775, 1.59526166 ,0.48598086,
 0.2063809 , 1.3777237,  0.08531313, 0.46286035 ,1.37174568, 0.38089566,
 1.67738095 ,0.66165392 ,0.76123835 ,1.86753907 ,0.27782602 ,1.38956582,
 0.34145884, 0.67803824 ,1.7586825  ,1.5506353 , 0.5955315 , 0.58244926,
 0.37391353, 0.41032079 ,0.34716825 ,0.15980737, 0.96261499 ,0.16353987])


In [31]:
x = float(input("Enter a number above 1000: "))
print("Value is {0:.3f}".format(x) )
print("Value is {0:.3e}".format(x) )

Enter a number above 1000:  342434.2343432


Value is 342434.234
Value is 3.424e+05


In [30]:
for i in range(len(rho)):
    if rho[i] < 0:
        print("Error: element {0:d} has a value of {1:.2f}".format(i,rho[i]) )
        break
        

Error: element 8 has a value of -0.78


In [33]:
for i in range(1,11):
    print("{0:d} * Pi = {1:.6f}".format(i,i*np.pi))

1 * Pi = 3.141593
2 * Pi = 6.283185
3 * Pi = 9.424778
4 * Pi = 12.566371
5 * Pi = 15.707963
6 * Pi = 18.849556
7 * Pi = 21.991149
8 * Pi = 25.132741
9 * Pi = 28.274334
10 * Pi = 31.415927
